### ISSUE TITLE
Add support for pyproject.toml to modernize package configuration

### ISSUE THREAD

**Issue by xerpi** [Navidfoumani/Series2Vec#9]
Thanks for the great work on this project!

I'd like to propose transitioning to the [`pyproject.toml`](https://peps.python.org/pep-0518/) standard for package configuration. This modern format is now widely supported across the Python ecosystem and enables compatibility with modern tools like [**uv**](https://github.com/astral-sh/uv) and [**rye**](https://github.com/astral-sh/rye).

### Benefits:

-   Cleaner and more unified configuration for build, dependencies, and tool-specific settings.
-   Easier environment management and dependency resolution with `uv` and `rye`.
-   Growing support and recommendation from Python Packaging Authority (PyPA).

**Comment by xerpi** [comment]
Here's a sample `pyproject.toml` that I've created to help get started:
```toml
[project]
name = "series2vec"
version = "0.1.0"
description = "DMKD-Series2Vec: Similarity-based Representation Learning for Time Series"
authors = [
    { name = "Navid Mohammadi Foumani" }
]
dependencies = [
    "absl-py==2.1.0",
    "asttokens==3.0.0",
    "backcall==0.2.0",
    "cachetools==5.5.2",
    "contourpy==1.1.1",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "einops==0.8.1",
    "executing==2.2.0",
    "filelock==3.13.1",
    "fonttools==4.56.0",
    "fsspec==2024.6.1",
    "git-filter-repo==2.47.0",
    "google-auth==2.38.0",
    "google-auth-oauthlib==1.0.0",
    "grpcio==1.70.0",
    "importlib-metadata==8.5.0",
    "importlib-resources==6.4.5",
    "ipdb==0.13.13",
    "ipython==8.12.3",
    "jedi==0.19.2",
    "jinja2==3.1.4",
    "joblib==1.4.2",
    "kiwisolver==1.4.7",
    "llvmlite>=0.44.0",
    "markdown==3.7",
    "markupsafe==2.1.5",
    "matplotlib==3.7.5",
    "matplotlib-inline==0.1.7",
    "mpmath==1.3.0",
    "networkx==3.0",
    "numba>=0.61.2",
    "oauthlib==3.2.2",
    "parso==0.8.4",
    "pexpect==4.9.0",
    "pickleshare==0.7.5",
    "pillow==10.2.0",
    "prompt-toolkit==3.0.50",
    "protobuf==5.29.3",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.1",
    "pygments==2.19.1",
    "pyparsing==3.1.4",
    "python-dateutil==2.9.0.post0",
    "requests-oauthlib==2.0.0",
    "rsa==4.9",
    "scikit-learn==1.3.2",
    "scipy>=1.15.2",
    "six==1.17.0",
    "stack-data==0.6.3",
    "sympy==1.13.1",
    "tabulate==0.9.0",
    "tensorboard==2.14.0",
    "tensorboard-data-server==0.7.2",
    "threadpoolctl==3.5.0",
    "torch==2.4.1+cu121",
    "torchaudio==2.4.1+cu121",
    "torchvision==0.19.1+cu121",
    "triton==3.0.0",
    "typing-extensions==4.12.2",
    "wcwidth==0.2.13",
    "werkzeug==3.0.6",
    "zipp==3.20.2",
]
readme = "README.md"
requires-python = ">= 3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/series2vec"]
```
